//! Decisive Adam parity vs PyTorch `torch.optim.AdamW`.
//!
//! Source: `HANDOFF_2026-05-24_ZIMAGE_VAE_FIXED_ADAM_AMP_OPEN.md` §10.
//!
//! The existing `tests/adam_f32_fused.rs` host reference implements OUR
//! kernel's WD ordering (Adam step first, then `p -= lr*wd*p` on the
//! stepped param). That ordering is NOT `torch.optim.AdamW` — PyTorch
//! applies `p *= (1 - lr*wd)` BEFORE the Adam update. The existing test
//! therefore guarantees self-consistency only, not PyTorch parity.
//!
//! This test compares our `AdamW::step` end state to torch.optim.AdamW
//! step-by-step on identical inputs across four scenarios:
//!   1. zimage/klein LoRA preset (single param, 5 steps, lr=3e-4, wd=0.01)
//!   2. Many tensors (50 params, exercises multi-tensor fused path)
//!   3. WD=0 (isolates non-WD math)
//!   4. Long horizon (50 steps at zimage preset — any compounding bug surfaces)
//!
//! Fixture generated by `tests/parity/adam_torch_parity_ref.py` and checked
//! in as `tests/parity/adam_torch_parity_ref.json`. On divergence, prints
//! WHICH case, WHICH step, and elementwise differences.

#![cfg(all(feature = "cuda", feature = "bf16_u16"))]

use flame_core::{adam::AdamW, global_cuda_device, Parameter, Result, Shape, Tensor};
use std::path::PathBuf;

#[derive(serde::Deserialize)]
struct Config {
    lr: f32,
    beta1: f32,
    beta2: f32,
    eps: f32,
    weight_decay: f32,
    n_per_tensor: usize,
    n_tensors: usize,
    steps: usize,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    config: Config,
    inits: Vec<Vec<f32>>,
    // grads[step][tensor] -> Vec<f32>
    grads: Vec<Vec<Vec<f32>>>,
    // p_after_step[step][tensor] -> Vec<f32>
    p_after_step: Vec<Vec<Vec<f32>>>,
}

#[derive(serde::Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("parity")
        .join("adam_torch_parity_ref.json")
}

fn load_fixture() -> Fixture {
    let path = fixture_path();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read parity fixture at {}: {}. \
             Regenerate via `python3 tests/parity/adam_torch_parity_ref.py`.",
            path.display(),
            e
        )
    });
    serde_json::from_slice(&bytes).expect("malformed parity fixture JSON")
}

fn run_case(c: &Case) -> Result<()> {
    let cfg = &c.config;
    assert_eq!(c.inits.len(), cfg.n_tensors);
    assert_eq!(c.grads.len(), cfg.steps);
    assert_eq!(c.p_after_step.len(), cfg.steps);
    for init in &c.inits {
        assert_eq!(init.len(), cfg.n_per_tensor);
    }
    for step_grads in &c.grads {
        assert_eq!(step_grads.len(), cfg.n_tensors);
        for g in step_grads {
            assert_eq!(g.len(), cfg.n_per_tensor);
        }
    }

    let device = global_cuda_device();
    let shape = Shape::from_dims(&[cfg.n_per_tensor]);

    // Build our params at the same init as the PyTorch reference.
    let mut params: Vec<Parameter> = Vec::with_capacity(cfg.n_tensors);
    for init in &c.inits {
        let t = Tensor::from_vec(init.clone(), shape.clone(), device.clone())?
            .requires_grad_(true);
        params.push(Parameter::new(t));
    }

    let mut opt = AdamW::new(cfg.lr, cfg.beta1, cfg.beta2, cfg.eps, cfg.weight_decay);

    // F32 fused kernel arithmetic — tolerance 5e-6 max-abs. With 50 steps at
    // ~1e-2 param magnitude this is comfortably above F32 round-off but well
    // below any real divergence we'd care about (the open bug shows 4×, not
    // sub-ULP).
    let tol: f32 = 5e-6;
    let mut first_diverging_step: Option<usize> = None;
    let mut diff_report = String::new();
    let mut step_max_abs: f32 = 0.0;

    for (k, (step_grads, ref_params)) in c.grads.iter().zip(c.p_after_step.iter()).enumerate() {
        for (p, g_vec) in params.iter().zip(step_grads.iter()) {
            let grad = Tensor::from_vec(g_vec.clone(), shape.clone(), device.clone())?;
            p.set_grad(grad)?;
        }
        opt.step(&params)?;

        let mut max_abs: f32 = 0.0;
        let mut argmax = (0usize, 0usize);
        for (ti, (p, ref_p)) in params.iter().zip(ref_params.iter()).enumerate() {
            let ours = p.tensor()?.to_vec_f32()?;
            for (i, (a, b)) in ours.iter().zip(ref_p.iter()).enumerate() {
                let d = (a - b).abs();
                if d > max_abs {
                    max_abs = d;
                    argmax = (ti, i);
                }
            }
        }
        step_max_abs = step_max_abs.max(max_abs);

        if max_abs > tol && first_diverging_step.is_none() {
            first_diverging_step = Some(k + 1);
            let (ti, ei) = argmax;
            let ours_full = params[ti].tensor()?.to_vec_f32()?;
            let ours = ours_full[ei];
            let theirs = ref_params[ti][ei];
            diff_report.push_str(&format!(
                "\n  >>> case '{}' first diverges at step {}/{}\n",
                c.name,
                k + 1,
                cfg.steps
            ));
            diff_report.push_str(&format!(
                "    worst elem: tensor {}, elem {}\n",
                ti, ei
            ));
            diff_report.push_str(&format!(
                "      ours   = {:+.10e}\n      torch  = {:+.10e}\n      diff   = {:+.3e}\n",
                ours,
                theirs,
                ours - theirs
            ));
            diff_report.push_str(&format!(
                "    max_abs={:.3e} (tolerance={:.0e})\n",
                max_abs, tol
            ));
        }
    }

    eprintln!(
        "[{:>22}] steps={:>2}  n_tensors={:>3}  n_per={:>3}  max_abs over all steps = {:.3e}",
        c.name, cfg.steps, cfg.n_tensors, cfg.n_per_tensor, step_max_abs
    );

    if let Some(s) = first_diverging_step {
        panic!(
            "flame-core AdamW diverges from torch.optim.AdamW: case='{}' step={}\n\
             N_per={} N_tensors={} lr={} betas=({}, {}) eps={} wd={}\n\
             {}",
            c.name,
            s,
            cfg.n_per_tensor,
            cfg.n_tensors,
            cfg.lr,
            cfg.beta1,
            cfg.beta2,
            cfg.eps,
            cfg.weight_decay,
            diff_report
        );
    }
    Ok(())
}

#[test]
fn adam_w_matches_pytorch_all_cases() -> Result<()> {
    let fx = load_fixture();
    assert!(!fx.cases.is_empty(), "fixture must contain at least one case");
    for c in &fx.cases {
        run_case(c)?;
    }
    Ok(())
}
