//! Phase 5a — autograd v2 PyTorch parity tests.
//!
//! 26 tests total (13 ops × {backward, forward-mode AD}). Each test
//! loads a PyTorch-generated fixture from `tests/fixtures/`, runs the
//! corresponding v2 op, and compares the produced gradients / output
//! tangent to the PyTorch reference via [`flame_core::parity::ParityHarness`].
//!
//! The fixtures are regenerated by:
//!
//!     python3 tests/fixtures/gen_v2_parity.py
//!
//! at `flame-core/` root, with `torch.manual_seed(42)`. The Python
//! script + the `.safetensors` outputs are all committed under
//! `tests/fixtures/`. The generator script reads as the reference
//! ground-truth definition for every op's parity expectation.
//!
//! ## Tolerance discipline
//!
//! - F32 paths: `min_cos = 0.99999`, `max_abs_ratio = 1e-4`. F32 ops
//!   should be bit-equal to PyTorch up to platform float ordering.
//! - BF16 paths (layer_norm only): `min_cos = 0.999`, `max_abs_ratio =
//!   5e-2`. The BF16 layer_norm backward kernel compounds BF16 noise
//!   through per-row reductions (mean / rstd / dweight via row-sums);
//!   single-row error budget per `BF16_GRAD_DECISION.md`.
//! - View ops (reshape/view/transpose/narrow/squeeze/unsqueeze/permute):
//!   F32 tolerance (no arithmetic; bit-equal).
//!
//! ## Coverage
//!
//! Backward (13):
//!  1. add                7. reshape
//!  2. mul                8. view
//!  3. sum                9. transpose
//!  4. matmul            10. narrow
//!  5. silu              11. squeeze
//!  6. layer_norm        12. unsqueeze
//!                       13. permute
//!
//! Forward-mode AD (13): same 13 ops, with `out_fw` parity instead of
//! `grad_input_*`. The layer_norm JVP formula is the Phase 5a-shipped
//! derivation (see `src/autograd_v2/ops/layer_norm.rs::layer_norm_jvp`).

#![cfg(all(feature = "cuda", feature = "bf16_u16", feature = "autograd_v2"))]

use std::path::PathBuf;
use std::sync::Arc;

use flame_core::autograd_v2::{
    new_meta_ref, AutogradMetaV2, DispatchCtx, Engine, GraphRoot,
};
use flame_core::parity::{ParityHarness, ParityTolerance};
use flame_core::serialization::{load_tensors, SerializationFormat};
use flame_core::{global_cuda_device, DType, Device, Tensor};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn default_ctx() -> DispatchCtx {
    let dev = Device::from_arc(global_cuda_device().clone());
    DispatchCtx::default_for(dev)
}

/// Attach a fresh `leaf_requires_grad` v2 autograd meta to a tensor
/// loaded from a fixture. Mirrors the helper in
/// `tests/autograd_v2_ops.rs::make_leaf_requires_grad`.
fn as_leaf_requires_grad(mut t: Tensor) -> Tensor {
    let meta = new_meta_ref(AutogradMetaV2::leaf_requires_grad());
    t.set_autograd_meta(Some(meta));
    t
}

/// Strict F32 tolerance — view-style and pure-F32-arithmetic ops.
fn tol_f32_tight() -> ParityTolerance {
    ParityTolerance {
        min_cos: 0.99999,
        max_abs_ratio: 1e-4,
    }
}

/// Relaxed F32 tolerance — arithmetic that compounds rounding (e.g.
/// matmul, sum reductions through the GpuOps F32 path).
fn tol_f32_loose() -> ParityTolerance {
    ParityTolerance {
        min_cos: 0.9999,
        max_abs_ratio: 5e-3,
    }
}

/// BF16 tolerance — layer_norm specifically. BF16 stats kernels
/// compound noise across the per-row reduction.
fn tol_bf16_ln() -> ParityTolerance {
    ParityTolerance {
        min_cos: 0.999,
        max_abs_ratio: 5e-2,
    }
}

/// Compute the param grad for a leaf after `Engine::execute`.
fn take_leaf_grad(t: &Tensor) -> Tensor {
    let meta = t.autograd_meta().expect("leaf has meta");
    let m = meta.lock().unwrap();
    m.grad.as_ref().expect("leaf has accumulated grad").clone()
}

fn load_fixture(name: &str) -> std::collections::HashMap<String, Tensor> {
    let path = fixtures_dir().join(name);
    let device = global_cuda_device().clone();
    load_tensors(&path, device, SerializationFormat::SafeTensors).expect("load fixture")
}

/// Drive the v2 engine end-to-end: backward through `out` with the
/// fixture's `grad_output`. The caller pre-sets the leaves'
/// `requires_grad` meta.
fn run_backward(out: Tensor, grad_output: Tensor, ctx: &DispatchCtx) {
    let root = GraphRoot::new(vec![out]).with_grad_outputs(vec![Some(grad_output)]);
    Engine::new().execute(root, ctx).expect("backward engine execute");
}

/// Take a fixture tensor and ensure it's the dtype the op expects.
fn cast_to(t: &Tensor, dt: DType) -> Tensor {
    if t.dtype() == dt {
        t.clone()
    } else {
        t.to_dtype(dt).expect("dtype cast")
    }
}

/// Open a ParityHarness on a fixture file with a chosen tolerance.
fn harness(fixture: &str, tol: ParityTolerance) -> ParityHarness {
    let path = fixtures_dir().join(fixture);
    let device = global_cuda_device().clone();
    ParityHarness::load(&path, device)
        .expect("load fixture")
        .with_tolerance(tol)
}

// ---------------------------------------------------------------------------
// Backward parity — 13 tests
// ---------------------------------------------------------------------------

#[test]
fn add_backward_matches_pytorch() {
    let f = load_fixture("add_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let b = as_leaf_requires_grad(cast_to(&f["input_1"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::add::add_v2(&a, &b, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("add_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    let _ = h.compare("grad_input_1", &take_leaf_grad(&b)).unwrap();
    h.assert_clean();
}

#[test]
fn mul_backward_matches_pytorch() {
    let f = load_fixture("mul_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let b = as_leaf_requires_grad(cast_to(&f["input_1"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::mul::mul_v2(&a, &b, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("mul_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    let _ = h.compare("grad_input_1", &take_leaf_grad(&b)).unwrap();
    h.assert_clean();
}

#[test]
fn sum_backward_matches_pytorch() {
    let f = load_fixture("sum_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::sum::sum_v2(&a, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("sum_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn matmul_backward_matches_pytorch() {
    let f = load_fixture("matmul_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let b = as_leaf_requires_grad(cast_to(&f["input_1"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::matmul::matmul_v2(&a, &b, &ctx).unwrap();
    run_backward(out, g, &ctx);
    // Matmul backward also runs through cuBLAS strided-batch; loose F32.
    let mut h = harness("matmul_backward.safetensors", tol_f32_loose());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    let _ = h.compare("grad_input_1", &take_leaf_grad(&b)).unwrap();
    h.assert_clean();
}

#[test]
fn silu_backward_matches_pytorch() {
    let f = load_fixture("silu_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::silu::silu_v2(&a, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("silu_backward.safetensors", tol_f32_loose());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn layer_norm_backward_matches_pytorch() {
    let f = load_fixture("layer_norm_backward.safetensors");
    // LN op is BF16-only.
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::BF16));
    let w = as_leaf_requires_grad(cast_to(&f["input_1"], DType::BF16));
    let b = as_leaf_requires_grad(cast_to(&f["input_2"], DType::BF16));
    let g = cast_to(&f["grad_output"], DType::BF16);
    let ctx = default_ctx();
    let normalized_shape = [w.shape().dims().last().copied().unwrap()];
    let out = flame_core::autograd_v2::ops::layer_norm::layer_norm_v2(
        &a,
        &normalized_shape,
        Some(&w),
        Some(&b),
        1e-5,
        &ctx,
    )
    .unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("layer_norm_backward.safetensors", tol_bf16_ln());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    let _ = h.compare("grad_input_1", &take_leaf_grad(&w)).unwrap();
    let _ = h.compare("grad_input_2", &take_leaf_grad(&b)).unwrap();
    h.assert_clean();
}

#[test]
fn reshape_backward_matches_pytorch() {
    let f = load_fixture("reshape_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let new_shape: Vec<usize> = f["grad_output"].shape().dims().to_vec();
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::reshape::reshape_v2(&a, &new_shape, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("reshape_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn view_backward_matches_pytorch() {
    let f = load_fixture("view_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let new_shape: Vec<usize> = f["grad_output"].shape().dims().to_vec();
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::reshape::view_v2(&a, &new_shape, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("view_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn transpose_backward_matches_pytorch() {
    let f = load_fixture("transpose_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::transpose::transpose_v2(&a, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("transpose_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn narrow_backward_matches_pytorch() {
    let f = load_fixture("narrow_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    // gen_v2_parity.py uses narrow(dim=1, start=2, length=5).
    let out = flame_core::autograd_v2::ops::narrow::narrow_v2(&a, 1, 2, 5, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("narrow_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn squeeze_backward_matches_pytorch() {
    let f = load_fixture("squeeze_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    // gen_v2_parity.py uses squeeze(dim=1).
    let out = flame_core::autograd_v2::ops::squeeze::squeeze_v2(&a, 1, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("squeeze_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn unsqueeze_backward_matches_pytorch() {
    let f = load_fixture("unsqueeze_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    // gen_v2_parity.py uses unsqueeze(dim=1).
    let out = flame_core::autograd_v2::ops::unsqueeze::unsqueeze_v2(&a, 1, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("unsqueeze_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

#[test]
fn permute_backward_matches_pytorch() {
    let f = load_fixture("permute_backward.safetensors");
    let a = as_leaf_requires_grad(cast_to(&f["input_0"], DType::F32));
    let g = cast_to(&f["grad_output"], DType::F32);
    let ctx = default_ctx();
    // gen_v2_parity.py uses permute(2, 0, 1).
    let perm = [2usize, 0, 1];
    let out = flame_core::autograd_v2::ops::permute::permute_v2(&a, &perm, &ctx).unwrap();
    run_backward(out, g, &ctx);
    let mut h = harness("permute_backward.safetensors", tol_f32_tight());
    let _ = h.compare("grad_input_0", &take_leaf_grad(&a)).unwrap();
    h.assert_clean();
}

// ---------------------------------------------------------------------------
// Forward-mode AD parity — 13 tests
// ---------------------------------------------------------------------------

/// Helper: install a tangent on a copy of `primal` and return it.
fn with_tangent(primal: &Tensor, tangent: &Tensor) -> Tensor {
    let mut t = primal.clone();
    t.set_fw_grad(tangent.clone());
    t
}

#[test]
fn add_jvp_matches_pytorch() {
    let f = load_fixture("add_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let b = with_tangent(&cast_to(&f["input_1"], DType::F32), &cast_to(&f["tangent_1"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::add::add_v2(&a, &b, &ctx).unwrap();
    let mut h = harness("add_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn mul_jvp_matches_pytorch() {
    let f = load_fixture("mul_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let b = with_tangent(&cast_to(&f["input_1"], DType::F32), &cast_to(&f["tangent_1"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::mul::mul_v2(&a, &b, &ctx).unwrap();
    let mut h = harness("mul_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn sum_jvp_matches_pytorch() {
    let f = load_fixture("sum_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::sum::sum_v2(&a, &ctx).unwrap();
    let mut h = harness("sum_jvp.safetensors", tol_f32_loose());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn matmul_jvp_matches_pytorch() {
    let f = load_fixture("matmul_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let b = with_tangent(&cast_to(&f["input_1"], DType::F32), &cast_to(&f["tangent_1"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::matmul::matmul_v2(&a, &b, &ctx).unwrap();
    let mut h = harness("matmul_jvp.safetensors", tol_f32_loose());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn silu_jvp_matches_pytorch() {
    let f = load_fixture("silu_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::silu::silu_v2(&a, &ctx).unwrap();
    let mut h = harness("silu_jvp.safetensors", tol_f32_loose());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn layer_norm_jvp_matches_pytorch() {
    let f = load_fixture("layer_norm_jvp.safetensors");
    let a = with_tangent(
        &cast_to(&f["input_0"], DType::BF16),
        &cast_to(&f["tangent_0"], DType::BF16),
    );
    let w = with_tangent(
        &cast_to(&f["input_1"], DType::BF16),
        &cast_to(&f["tangent_1"], DType::BF16),
    );
    let b = with_tangent(
        &cast_to(&f["input_2"], DType::BF16),
        &cast_to(&f["tangent_2"], DType::BF16),
    );
    let ctx = default_ctx();
    let normalized_shape = [w.shape().dims().last().copied().unwrap()];
    let out = flame_core::autograd_v2::ops::layer_norm::layer_norm_v2(
        &a,
        &normalized_shape,
        Some(&w),
        Some(&b),
        1e-5,
        &ctx,
    )
    .unwrap();
    let mut h = harness("layer_norm_jvp.safetensors", tol_bf16_ln());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn reshape_jvp_matches_pytorch() {
    let f = load_fixture("reshape_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let new_shape: Vec<usize> = f["out_fw"].shape().dims().to_vec();
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::reshape::reshape_v2(&a, &new_shape, &ctx).unwrap();
    let mut h = harness("reshape_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn view_jvp_matches_pytorch() {
    let f = load_fixture("view_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let new_shape: Vec<usize> = f["out_fw"].shape().dims().to_vec();
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::reshape::view_v2(&a, &new_shape, &ctx).unwrap();
    let mut h = harness("view_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn transpose_jvp_matches_pytorch() {
    let f = load_fixture("transpose_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::transpose::transpose_v2(&a, &ctx).unwrap();
    let mut h = harness("transpose_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn narrow_jvp_matches_pytorch() {
    let f = load_fixture("narrow_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::narrow::narrow_v2(&a, 1, 2, 5, &ctx).unwrap();
    let mut h = harness("narrow_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn squeeze_jvp_matches_pytorch() {
    let f = load_fixture("squeeze_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::squeeze::squeeze_v2(&a, 1, &ctx).unwrap();
    let mut h = harness("squeeze_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn unsqueeze_jvp_matches_pytorch() {
    let f = load_fixture("unsqueeze_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let out = flame_core::autograd_v2::ops::unsqueeze::unsqueeze_v2(&a, 1, &ctx).unwrap();
    let mut h = harness("unsqueeze_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

#[test]
fn permute_jvp_matches_pytorch() {
    let f = load_fixture("permute_jvp.safetensors");
    let a = with_tangent(&cast_to(&f["input_0"], DType::F32), &cast_to(&f["tangent_0"], DType::F32));
    let ctx = default_ctx();
    let perm = [2usize, 0, 1];
    let out = flame_core::autograd_v2::ops::permute::permute_v2(&a, &perm, &ctx).unwrap();
    let mut h = harness("permute_jvp.safetensors", tol_f32_tight());
    let _ = h.compare("out_fw", &out.fw_grad().expect("out_fw")).unwrap();
    h.assert_clean();
}

// Keep `Arc` referenced so unused-import warnings stay silent if future
// refactors drop helpers that referenced it directly.
#[allow(dead_code)]
fn _arc_anchor(_: Arc<()>) {}
