//! Parity smoke test (Fusion Sprint Phase 0).
//!
//! Three things this test guards:
//!
//!   1. The fixture loader actually loads the bytes we expect (SHA256-pinned).
//!   2. `compare_bf16` recognizes a known-good output (a + b == fixture.output).
//!   3. `compare_bf16` actually FAILS when given a deliberately-wrong tensor
//!      (a + 1.0 should not equal a) — i.e. the comparator isn't a sham.
//!
//! Smoke fixture was generated by:
//!
//! ```text
//! torch.manual_seed(0); torch.cuda.manual_seed(0)
//! a = torch.randn(4, 8, device='cuda', dtype=torch.bfloat16)
//! b = torch.randn(4, 8, device='cuda', dtype=torch.bfloat16)
//! save_file({"input_a": a, "input_b": b, "output": a+b}, ...)
//! ```
//!
//! Pinned SHA256 (over fixture file bytes) is asserted at the top of every
//! smoke run. If you regenerate the fixture, update the constant.

#![cfg(all(feature = "cuda", feature = "bf16_u16"))]

mod parity_helpers;

use flame_core::{global_cuda_device, serialization::load_file};
use std::path::PathBuf;

const FIXTURE_REL: &str = "tests/pytorch_fixtures/smoke/add_4x8_bf16.safetensors";
const FIXTURE_SHA256: &str = "ddde4d62922baf2969a0eba1b8db813580b1dbc9f37fcc66ef9e8110dc1a5086";

fn fixture_path() -> PathBuf {
    // Resolve relative to the flame-core crate root regardless of cwd.
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_root.join(FIXTURE_REL)
}

#[test]
fn smoke_fixture_sha256_matches_pin() {
    let p = fixture_path();
    assert!(
        p.exists(),
        "fixture missing: {p:?}\n\
         regenerate with `python scripts/generate_pytorch_fixtures.py` or the inline snippet \
         in parity_smoke.rs"
    );
    let actual = parity_helpers::sha256_file(&p);
    assert_eq!(
        actual, FIXTURE_SHA256,
        "smoke fixture SHA256 drift — file at {p:?} does not match pinned hash {FIXTURE_SHA256}.\n\
         If you regenerated the fixture intentionally, update FIXTURE_SHA256 in parity_smoke.rs.\n\
         actual: {actual}"
    );
}

#[test]
fn smoke_add_matches_pytorch_oracle() {
    let dev = global_cuda_device();
    let p = fixture_path();
    assert_eq!(
        parity_helpers::sha256_file(&p),
        FIXTURE_SHA256,
        "fixture sha drift"
    );

    let tensors = load_file(&p, &dev).expect("load smoke fixture");
    let a = tensors.get("input_a").expect("missing input_a");
    let b = tensors.get("input_b").expect("missing input_b");
    let expected = tensors.get("output").expect("missing output");

    let got = a.add(b).expect("add failed");

    let report = parity_helpers::compare_bf16(&got, expected);
    assert!(report.passed, "smoke add: parity FAIL\n{}", report.pretty());
    eprintln!("smoke add ok: {}", report.pretty());
}

/// Sanity check on the comparator itself — give it a known-bad input and
/// confirm it fails. If this passes, the comparator is broken.
#[test]
fn smoke_comparator_catches_known_mismatch() {
    let dev = global_cuda_device();
    let p = fixture_path();

    let tensors = load_file(&p, &dev).expect("load smoke fixture");
    let a = tensors.get("input_a").expect("missing input_a");
    let expected = tensors.get("output").expect("missing output");

    // Deliberately wrong: compare `a` against `a + b` (== expected).
    // |Δ| ≈ |b| which is O(1) for randn — way above atol=1e-2.
    let report = parity_helpers::compare_bf16(a, expected);
    assert!(
        !report.passed,
        "comparator failed to detect deliberate mismatch — broken!\n{}",
        report.pretty()
    );
    // Sanity: top-K should be populated and non-zero.
    assert!(!report.top_k.is_empty(), "top_k empty on mismatch");
    assert!(
        report.top_k[0].3 > 0.0,
        "top_k entry has zero delta: {:?}",
        report.top_k[0]
    );
    eprintln!(
        "comparator correctly flagged mismatch:\n{}",
        report.pretty()
    );
}

/// Also exercise the FP32-reduction tolerance pathway with a synthetic
/// scalar comparison. Guards against accidentally promoting the
/// reduction-tolerance path to BF16 atol.
#[test]
fn smoke_fp32_reduction_tolerance_is_tight() {
    use flame_core::{Shape, Tensor};
    let dev = global_cuda_device();
    // Two FP32 scalars within tight FP32-reduction tol (atol=1e-5).
    let a = Tensor::from_vec(vec![1.0_f32], Shape::from_dims(&[1]), dev.clone()).unwrap();
    let b = Tensor::from_vec(vec![1.0_f32 + 4e-7], Shape::from_dims(&[1]), dev.clone()).unwrap();
    let r = parity_helpers::compare_fp32_reduction(&a, &b);
    assert!(
        r.passed,
        "FP32-reduction tol unexpectedly failed: {}",
        r.pretty()
    );

    // Clearly outside FP32-reduction tol.
    let c = Tensor::from_vec(vec![1.0_f32 + 1e-3], Shape::from_dims(&[1]), dev.clone()).unwrap();
    let r2 = parity_helpers::compare_fp32_reduction(&a, &c);
    assert!(
        !r2.passed,
        "FP32-reduction tol unexpectedly accepted 1e-3 drift: {}",
        r2.pretty()
    );
}
