//! PyTorch-oracle parity tests.
//!
//! Loads fixtures generated by `scripts/generate_pytorch_fixtures.py` and
//! compares flame-core's op output against PyTorch's, element-wise. PyTorch
//! is the source of truth — no circular comparisons.
//!
//! Run:
//!   PYTORCH_FIXTURES=tests/pytorch_fixtures/ cargo test --release --test pytorch_parity
//!
//! Perf table (prints, does not gate):
//!   PYTORCH_FIXTURES=tests/pytorch_fixtures/ \
//!     cargo test --release --test pytorch_parity perf_comparison -- --ignored --nocapture
//!
//! ## Adaptation notes (from the original drop)
//!
//! The original `pytorch_parity.rs` was authored against a generic PyTorch-
//! style op surface. flame-core diverges in a few places that matter here:
//!
//!   - Op results are `flame_core::Result<Tensor>`, not `anyhow::Result`.
//!   - Comparison ops (`gt`/`ge`/`lt`/`le`/`eq`/`ne`) return BF16 0.0/1.0
//!     sentinels, not bool/u8 (see CONVENTIONS.md). PyTorch returns bool.
//!     We cast PyTorch's output to f32 0/1 and compare bit-for-bit.
//!   - `Tensor::eq` / `Tensor::ne` (not `eq_tensor`/`ne_tensor`).
//!   - No `Tensor::linear` / `Tensor::conv2d` methods in flame-core —
//!     those call sites use standalone `ops::fused_inference` functions
//!     or `conv::Conv2d`. For the generic parity here we use the
//!     decomposed matmul+bias form; conv2d is `#[ignore]`d pending a
//!     dedicated conv parity test.
//!   - `swiglu_fused_bf16(gate, up)` takes two tensors; the fixture saves
//!     a packed `[B, N, 2D]` input, so we narrow it in half first.
//!   - `fused_rms_norm` lives at `ops::fused_inference::fused_rms_norm`.

#![cfg(all(feature = "cuda", feature = "bf16_u16"))]

use flame_core::{Error, Result, Tensor};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

// ---------------------------------------------------------------------------
// Test infrastructure
// ---------------------------------------------------------------------------

fn fixtures_dir() -> PathBuf {
    PathBuf::from(
        std::env::var("PYTORCH_FIXTURES").unwrap_or_else(|_| "tests/pytorch_fixtures".to_string()),
    )
}

fn skip_if_no_fixtures() -> bool {
    let dir = fixtures_dir();
    if !dir.exists() {
        eprintln!(
            "SKIP: fixtures dir {:?} not found. Run scripts/generate_pytorch_fixtures.py first.",
            dir
        );
        true
    } else {
        false
    }
}

/// Load a safetensors fixture file into GPU tensors. Routes through
/// `flame_core::serialization::load_file`, which is the same path used by
/// inference-flame to load model weights — so we test the same code path
/// our production model loads go through.
fn load_fixture(path: &Path) -> HashMap<String, Tensor> {
    let device = flame_core::global_cuda_device();
    flame_core::serialization::load_file(path, &device)
        .unwrap_or_else(|e| panic!("load_file {:?} failed: {:?}", path, e))
}

/// BF16 bit-exact length-match. Returns the mismatch count (0 = bit-exact).
fn count_bf16_mismatches(got: &Tensor, expected: &Tensor) -> usize {
    let got_bits = got.to_vec_bf16().expect("to_vec_bf16 on got");
    let exp_bits = expected.to_vec_bf16().expect("to_vec_bf16 on expected");
    assert_eq!(
        got_bits.len(),
        exp_bits.len(),
        "length mismatch: got {} vs expected {}",
        got_bits.len(),
        exp_bits.len()
    );
    got_bits
        .iter()
        .zip(exp_bits.iter())
        .filter(|(a, b)| a != b)
        .count()
}

fn cos_sim_f32(got: &Tensor, expected: &Tensor) -> f64 {
    let gf = got.to_vec_f32().expect("to_vec_f32 on got");
    let ef = expected.to_vec_f32().expect("to_vec_f32 on expected");
    assert_eq!(gf.len(), ef.len(), "cos_sim length mismatch");
    let dot: f64 = gf
        .iter()
        .zip(ef.iter())
        .map(|(a, b)| *a as f64 * *b as f64)
        .sum();
    let na: f64 = gf.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    let nb: f64 = ef.iter().map(|x| (*x as f64).powi(2)).sum::<f64>().sqrt();
    if na == 0.0 || nb == 0.0 {
        0.0
    } else {
        dot / (na * nb)
    }
}

fn max_abs_diff(got: &Tensor, expected: &Tensor) -> f32 {
    let gf = got.to_vec_f32().expect("to_vec_f32 on got");
    let ef = expected.to_vec_f32().expect("to_vec_f32 on expected");
    gf.iter()
        .zip(ef.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max)
}

fn assert_cos_sim(name: &str, got: &Tensor, expected: &Tensor, threshold: f64) {
    let cos = cos_sim_f32(got, expected);
    assert!(
        cos >= threshold,
        "{name}: cos_sim = {cos:.8} < threshold {threshold} (max_abs_diff {:.4e})",
        max_abs_diff(got, expected)
    );
}

fn discover_fixtures(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return vec![];
    }
    let mut files: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|_| panic!("Failed to read dir {:?}", dir))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map_or(false, |ext| ext == "safetensors"))
        .collect();
    files.sort();
    files
}

// ---------------------------------------------------------------------------
// Section 1: Unary op parity
// ---------------------------------------------------------------------------

fn run_unary_test(op_name: &str, op_fn: fn(&Tensor) -> Result<Tensor>) {
    if skip_if_no_fixtures() {
        return;
    }

    let dir = fixtures_dir().join("unary").join(op_name);
    let fixtures = discover_fixtures(&dir);
    assert!(
        !fixtures.is_empty(),
        "No fixtures found for unary/{op_name} at {dir:?}"
    );

    for fixture_path in &fixtures {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        let tensors = load_fixture(fixture_path);
        let input = tensors.get("input").expect("missing 'input' in fixture");
        let expected = tensors.get("output").expect("missing 'output' in fixture");

        let got = op_fn(input).unwrap_or_else(|e| panic!("{op_name}/{stem}: op failed: {e:?}"));

        let mismatches = count_bf16_mismatches(&got, expected);
        if mismatches == 0 {
            println!("  {op_name}/{stem}: bit-exact");
        } else {
            let cos = cos_sim_f32(&got, expected);
            let mad = max_abs_diff(&got, expected);
            println!(
                "  {op_name}/{stem}: cos_sim={cos:.8} max_abs_diff={mad:.4e} ({mismatches} bf16 bits differ)"
            );
            assert!(
                cos >= 0.9999,
                "{op_name}/{stem}: cos_sim {cos:.8} < 0.9999"
            );
        }
    }
}

#[test] fn parity_unary_silu()    { run_unary_test("silu",    |x| x.silu()); }
#[test] fn parity_unary_gelu()    { run_unary_test("gelu",    |x| x.gelu()); }
#[test] fn parity_unary_relu()    { run_unary_test("relu",    |x| x.relu()); }
#[test] fn parity_unary_sigmoid() { run_unary_test("sigmoid", |x| x.sigmoid()); }
#[test] fn parity_unary_tanh()    { run_unary_test("tanh",    |x| x.tanh()); }
#[test] fn parity_unary_abs()     { run_unary_test("abs",     |x| x.abs()); }
#[test] fn parity_unary_neg()     { run_unary_test("neg",     |x| x.neg()); }
#[test] fn parity_unary_square()  { run_unary_test("square",  |x| x.square()); }
#[test] fn parity_unary_exp()     { run_unary_test("exp",     |x| x.exp()); }
#[test] fn parity_unary_log()     { run_unary_test("log",     |x| x.log()); }
#[test] fn parity_unary_sqrt()    { run_unary_test("sqrt",    |x| x.sqrt()); }
#[test] fn parity_unary_rsqrt()   { run_unary_test("rsqrt",   |x| x.rsqrt()); }
#[test] fn parity_unary_recip()   { run_unary_test("recip",   |x| x.reciprocal()); }

// ---------------------------------------------------------------------------
// Section 2: Binary op parity
// ---------------------------------------------------------------------------

fn run_binary_test(op_name: &str, op_fn: fn(&Tensor, &Tensor) -> Result<Tensor>) {
    if skip_if_no_fixtures() {
        return;
    }

    let dir = fixtures_dir().join("binary").join(op_name);
    let fixtures = discover_fixtures(&dir);
    assert!(!fixtures.is_empty(), "No fixtures for binary/{op_name}");

    for fixture_path in &fixtures {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        let tensors = load_fixture(fixture_path);
        let a = tensors.get("input_a").expect("missing 'input_a'");
        let b = tensors.get("input_b").expect("missing 'input_b'");
        let expected = tensors.get("output").expect("missing 'output'");

        let got = op_fn(a, b).unwrap_or_else(|e| panic!("{op_name}/{stem}: op failed: {e:?}"));

        let mismatches = count_bf16_mismatches(&got, expected);
        if mismatches == 0 {
            println!("  {op_name}/{stem}: bit-exact");
        } else {
            let cos = cos_sim_f32(&got, expected);
            let mad = max_abs_diff(&got, expected);
            println!(
                "  {op_name}/{stem}: cos_sim={cos:.8} max_abs_diff={mad:.4e} ({mismatches} bf16 bits differ)"
            );
            assert!(
                cos >= 0.9999,
                "{op_name}/{stem}: cos_sim {cos:.8} < 0.9999"
            );
        }
    }
}

#[test] fn parity_binary_add()     { run_binary_test("add",     |a, b| a.add(b)); }
#[test] fn parity_binary_sub()     { run_binary_test("sub",     |a, b| a.sub(b)); }
#[test] fn parity_binary_mul()     { run_binary_test("mul",     |a, b| a.mul(b)); }
#[test] fn parity_binary_div()     { run_binary_test("div",     |a, b| a.div(b)); }
#[test] fn parity_binary_maximum() { run_binary_test("maximum", |a, b| a.maximum(b)); }
#[test] fn parity_binary_minimum() { run_binary_test("minimum", |a, b| a.minimum(b)); }

// ---------------------------------------------------------------------------
// Section 3: Scalar op parity
// ---------------------------------------------------------------------------

#[test]
fn parity_scalar_add() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("scalar").join("add_scalar");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        let tensors = load_fixture(&fixture_path);
        let input = tensors.get("input").unwrap();
        let expected = tensors.get("output").unwrap();
        let got = input.add_scalar(0.5).unwrap();
        assert_cos_sim(&format!("add_scalar/{stem}"), &got, expected, 0.9999);
        println!("  add_scalar/{stem}: ok");
    }
}

#[test]
fn parity_scalar_mul() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("scalar").join("mul_scalar");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        let tensors = load_fixture(&fixture_path);
        let input = tensors.get("input").unwrap();
        let expected = tensors.get("output").unwrap();
        let got = input.mul_scalar(2.0).unwrap();
        assert_cos_sim(&format!("mul_scalar/{stem}"), &got, expected, 0.9999);
        println!("  mul_scalar/{stem}: ok");
    }
}

// ---------------------------------------------------------------------------
// Section 4: Comparison op parity
// ---------------------------------------------------------------------------
//
// flame-core's comparison ops return BF16 0.0/1.0 sentinels (see
// CONVENTIONS.md). PyTorch returns bool. The Python fixture saves PyTorch's
// bool output as u8 via safetensors; when loaded through flame-core's
// serialization it becomes a U8 tensor. We cast it to f32 0.0/1.0 and
// compare against the BF16 0.0/1.0 flame-core produces. Bit-exact match
// required — they're either 0 or 1 with no precision in between.

fn run_comparison_test(op_name: &str, op_fn: fn(&Tensor, &Tensor) -> Result<Tensor>) {
    if skip_if_no_fixtures() { return; }

    let dir = fixtures_dir().join("comparison").join(op_name);
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        let tensors = load_fixture(&fixture_path);
        let a = tensors.get("input_a").unwrap();
        let b = tensors.get("input_b").unwrap();
        let expected = tensors.get("output").unwrap();

        let got = op_fn(a, b).unwrap_or_else(|e| panic!("{op_name}/{stem}: op failed: {e:?}"));

        let got_f = got.to_vec_f32().unwrap();
        let exp_f = expected.to_vec_f32().unwrap();
        assert_eq!(
            got_f.len(), exp_f.len(),
            "{op_name}/{stem}: length mismatch"
        );
        let mismatches: Vec<usize> = got_f
            .iter()
            .zip(exp_f.iter())
            .enumerate()
            .filter(|(_, (g, e))| (*g - *e).abs() > 0.0)
            .map(|(i, _)| i)
            .collect();
        assert!(
            mismatches.is_empty(),
            "{op_name}/{stem}: {}/{} elements differ. First mismatches: {:?}",
            mismatches.len(),
            got_f.len(),
            &mismatches[..mismatches.len().min(10)]
        );
        println!("  {op_name}/{stem}: bit-exact");
    }
}

#[test] fn parity_cmp_gt() { run_comparison_test("gt", |a, b| a.gt(b)); }
#[test] fn parity_cmp_ge() { run_comparison_test("ge", |a, b| a.ge(b)); }
#[test] fn parity_cmp_lt() { run_comparison_test("lt", |a, b| a.lt(b)); }
#[test] fn parity_cmp_le() { run_comparison_test("le", |a, b| a.le(b)); }
#[test] fn parity_cmp_eq() { run_comparison_test("eq", |a, b| a.eq(b)); }
#[test] fn parity_cmp_ne() { run_comparison_test("ne", |a, b| a.ne(b)); }

// ---------------------------------------------------------------------------
// Section 5: SDPA parity
// ---------------------------------------------------------------------------

#[test]
fn parity_sdpa_contiguous() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("sdpa");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if !stem.ends_with("_contig") { continue; }

        let tensors = load_fixture(&fixture_path);
        let q = tensors.get("q").unwrap();
        let k = tensors.get("k").unwrap();
        let v = tensors.get("v").unwrap();
        let expected = tensors.get("output").unwrap();

        let got = flame_core::sdpa::forward(q, k, v, None)
            .unwrap_or_else(|e| panic!("sdpa/{stem}: op failed: {e:?}"));
        assert_cos_sim(&format!("sdpa/{stem}"), &got, expected, 0.999);
        println!("  sdpa/{stem}: ok");
    }
}

// Strided SDPA parity — the strided fixture materializes the post-permute
// contiguous tensor on the Python side, so the values already match what
// flame-core sees after permute+contiguous. True strided-view parity lives
// in `tests/cudnn_sdpa_parity.rs` (which uses flame-core's narrow/permute
// directly). This test just documents the fixture exists.
#[test]
fn parity_sdpa_strided_placeholder() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("sdpa");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if !stem.ends_with("_strided") { continue; }
        let tensors = load_fixture(&fixture_path);
        let q = tensors.get("q").unwrap();
        let k = tensors.get("k").unwrap();
        let v = tensors.get("v").unwrap();
        let expected = tensors.get("output").unwrap();

        let got = flame_core::sdpa::forward(q, k, v, None)
            .unwrap_or_else(|e| panic!("sdpa/{stem}: op failed: {e:?}"));
        assert_cos_sim(&format!("sdpa/{stem}"), &got, expected, 0.999);
        println!("  sdpa/{stem}: ok (post-permute-contig values)");
    }
}

// ---------------------------------------------------------------------------
// Section 6: Matmul / Linear parity
// ---------------------------------------------------------------------------
//
// PyTorch's `F.linear(x, w, b)` = `x @ w.T + b`. flame-core has no
// `Tensor::linear` method; the inference hot path uses
// `ops::fused_inference::fused_linear3d_native` which expects weight in
// PyTorch-native `[out, in]` layout. For generic 2D matmul we use
// `Tensor::matmul` against the weight's transpose, then add bias.

#[test]
fn parity_matmul_linear() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("matmul");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if stem.ends_with("_nobias") { continue; }

        let tensors = load_fixture(&fixture_path);
        let input = tensors.get("input").unwrap();
        let weight = tensors.get("weight").unwrap();
        let bias = tensors.get("bias").unwrap();
        let expected = tensors.get("output").unwrap();

        let w_t = weight.transpose().unwrap();
        let logits = input.matmul(&w_t).unwrap();
        let got = logits.add(bias).unwrap();
        assert_cos_sim(&format!("linear/{stem}"), &got, expected, 0.999);
        println!("  linear/{stem}: ok");
    }
}

#[test]
fn parity_matmul_nobias() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("matmul");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if !stem.ends_with("_nobias") { continue; }

        let tensors = load_fixture(&fixture_path);
        let input = tensors.get("input").unwrap();
        let weight = tensors.get("weight").unwrap();
        let expected = tensors.get("output").unwrap();

        let w_t = weight.transpose().unwrap();
        let got = input.matmul(&w_t).unwrap();
        assert_cos_sim(&format!("matmul/{stem}"), &got, expected, 0.999);
        println!("  matmul/{stem}: ok");
    }
}

// ---------------------------------------------------------------------------
// Section 7: Conv2d parity
// ---------------------------------------------------------------------------

#[test]
#[ignore] // Needs flame_core::conv::Conv2d wrapping; pending a dedicated conv parity test.
fn parity_conv2d() {
    if skip_if_no_fixtures() { return; }
    println!("conv2d parity pending dedicated implementation");
}

// ---------------------------------------------------------------------------
// Section 8: Fused-op parity (where flame-core should be faster than PyTorch)
// ---------------------------------------------------------------------------

#[test]
fn parity_fused_swiglu() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("fused");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if !stem.starts_with("swiglu_") { continue; }

        let tensors = load_fixture(&fixture_path);
        let gate_up = tensors.get("input").unwrap();
        let expected = tensors.get("output").unwrap();

        // flame-core's swiglu takes (gate, up) as separate tensors.
        // Fixture packs them as [B, N, 2D] on the last dim.
        let dims = gate_up.shape().dims();
        let last = *dims.last().expect("swiglu: empty shape");
        assert_eq!(last % 2, 0, "swiglu/{stem}: last dim {last} not even");
        let half = last / 2;
        let last_axis = dims.len() - 1;
        let gate = gate_up.narrow(last_axis, 0, half).unwrap();
        let up = gate_up.narrow(last_axis, half, half).unwrap();
        let got = flame_core::bf16_ops::swiglu_fused_bf16(&gate, &up).unwrap();
        assert_cos_sim(&format!("swiglu/{stem}"), &got, expected, 0.9999);
        println!("  swiglu/{stem}: ok");
    }
}

#[test]
fn parity_fused_rmsnorm() {
    if skip_if_no_fixtures() { return; }
    let dir = fixtures_dir().join("fused");
    for fixture_path in discover_fixtures(&dir) {
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap();
        if !stem.starts_with("rmsnorm_") { continue; }

        let tensors = load_fixture(&fixture_path);
        let input = tensors.get("input").unwrap();
        let weight = tensors.get("weight").unwrap();
        let expected = tensors.get("output").unwrap();

        let got = flame_core::ops::fused_inference::fused_rms_norm(input, weight, 1e-5)
            .unwrap_or_else(|e| panic!("rmsnorm/{stem}: op failed: {e:?}"));
        assert_cos_sim(&format!("rmsnorm/{stem}"), &got, expected, 0.999);
        println!("  rmsnorm/{stem}: ok");
    }
}

// ---------------------------------------------------------------------------
// Section 9: Pattern parity (combined sequences)
// ---------------------------------------------------------------------------

#[test]
#[ignore] // Requires reconstructing the pattern with matching weights; see fixture README.
fn parity_pattern_klein_double_block() {
    println!("klein_double_block pattern test pending weight-reconstruction infra");
}

// ---------------------------------------------------------------------------
// Section 10: Performance comparison
// ---------------------------------------------------------------------------
//
// Run explicitly: `cargo test --release --test pytorch_parity perf_comparison
// -- --ignored --nocapture`. Does NOT assert on timing — just reports.

fn device_sync() -> Result<()> {
    let device = flame_core::global_cuda_device();
    device
        .synchronize()
        .map_err(|e| Error::Cuda(format!("synchronize: {:?}", e)))
}

fn bench_flame<F: FnMut() -> Result<()>>(mut f: F, warmup: usize, iters: usize) -> f64 {
    for _ in 0..warmup {
        let _ = f();
    }
    let _ = device_sync();
    let mut times = Vec::with_capacity(iters);
    for _ in 0..iters {
        let _ = device_sync();
        let t0 = Instant::now();
        let _ = f();
        let _ = device_sync();
        times.push(t0.elapsed().as_nanos() as f64 / 1000.0);
    }
    times.sort_by(|a, b| a.partial_cmp(b).unwrap());
    times[times.len() / 2]
}

/// Try to run a flame-core equivalent for the given (category, op, shape
/// fixture name). Returns `None` if the category/op isn't wired up here yet.
fn bench_flame_for(op_path: &str, shape_name: &str) -> Option<f64> {
    // op_path has the form "unary/silu", "binary/add", "scalar/add_scalar",
    // "comparison/gt", etc.
    let mut parts = op_path.splitn(2, '/');
    let category = parts.next()?;
    let op = parts.next()?;
    let root = fixtures_dir();

    // Unary ops
    if category == "unary" {
        let path = root.join("unary").join(op).join(format!("{shape_name}.safetensors"));
        if !path.exists() { return None; }
        let ts = load_fixture(&path);
        let x = ts.get("input")?.clone();
        let f: fn(&Tensor) -> Result<Tensor> = match op {
            "silu"    => |t| t.silu(),
            "gelu"    => |t| t.gelu(),
            "relu"    => |t| t.relu(),
            "sigmoid" => |t| t.sigmoid(),
            "tanh"    => |t| t.tanh(),
            "abs"     => |t| t.abs(),
            "neg"     => |t| t.neg(),
            "square"  => |t| t.square(),
            "exp"     => |t| t.exp(),
            "log"     => |t| t.log(),
            "sqrt"    => |t| t.sqrt(),
            "rsqrt"   => |t| t.rsqrt(),
            "recip"   => |t| t.reciprocal(),
            _ => return None,
        };
        return Some(bench_flame(|| { let _ = f(&x)?; Ok(()) }, 3, 10));
    }

    // Binary ops
    if category == "binary" {
        let path = root.join("binary").join(op).join(format!("{shape_name}.safetensors"));
        if !path.exists() { return None; }
        let ts = load_fixture(&path);
        let a = ts.get("input_a")?.clone();
        let b = ts.get("input_b")?.clone();
        let f: fn(&Tensor, &Tensor) -> Result<Tensor> = match op {
            "add"     => |x, y| x.add(y),
            "sub"     => |x, y| x.sub(y),
            "mul"     => |x, y| x.mul(y),
            "div"     => |x, y| x.div(y),
            "maximum" => |x, y| x.maximum(y),
            "minimum" => |x, y| x.minimum(y),
            _ => return None,
        };
        return Some(bench_flame(|| { let _ = f(&a, &b)?; Ok(()) }, 3, 10));
    }

    // Scalar ops
    if category == "scalar" {
        let path = root.join("scalar").join(op).join(format!("{shape_name}.safetensors"));
        if !path.exists() { return None; }
        let ts = load_fixture(&path);
        let x = ts.get("input")?.clone();
        return Some(match op {
            "add_scalar" => bench_flame(|| { let _ = x.add_scalar(0.5)?; Ok(()) }, 3, 10),
            "mul_scalar" => bench_flame(|| { let _ = x.mul_scalar(2.0)?; Ok(()) }, 3, 10),
            _ => return None,
        });
    }

    // Comparison ops
    if category == "comparison" {
        let path = root.join("comparison").join(op).join(format!("{shape_name}.safetensors"));
        if !path.exists() { return None; }
        let ts = load_fixture(&path);
        let a = ts.get("input_a")?.clone();
        let b = ts.get("input_b")?.clone();
        let f: fn(&Tensor, &Tensor) -> Result<Tensor> = match op {
            "gt" => |x, y| x.gt(y),
            "ge" => |x, y| x.ge(y),
            "lt" => |x, y| x.lt(y),
            "le" => |x, y| x.le(y),
            "eq" => |x, y| x.eq(y),
            "ne" => |x, y| x.ne(y),
            _ => return None,
        };
        return Some(bench_flame(|| { let _ = f(&a, &b)?; Ok(()) }, 3, 10));
    }

    // SDPA
    if category == "sdpa" {
        // op here is actually the shape name for sdpa (no sub-op)
        let path = root.join("sdpa").join(format!("{shape_name}.safetensors"));
        if !path.exists() { return None; }
        let ts = load_fixture(&path);
        let q = ts.get("q")?.clone();
        let k = ts.get("k")?.clone();
        let v = ts.get("v")?.clone();
        return Some(bench_flame(
            || { let _ = flame_core::sdpa::forward(&q, &k, &v, None)?; Ok(()) },
            3, 10,
        ));
    }

    None
}

#[test]
#[ignore]
fn perf_comparison() {
    if skip_if_no_fixtures() { return; }

    let timing_path = fixtures_dir().join("timing_results.json");
    if !timing_path.exists() {
        println!("No timing_results.json found — skipping perf comparison");
        return;
    }

    let timing_json: Vec<serde_json::Value> = {
        let data = fs::read_to_string(&timing_path).unwrap();
        serde_json::from_str(&data).unwrap()
    };

    println!();
    println!(
        "{:<35} {:<28} {:>12} {:>12} {:>10}",
        "op", "shape", "PyTorch µs", "flame µs", "ratio"
    );
    println!("{}", "-".repeat(100));

    for entry in &timing_json {
        let op = entry["op"].as_str().unwrap_or("");
        let shape_name = entry["shape_name"].as_str().unwrap_or("");
        let pytorch_us = entry["median_us"].as_f64().unwrap_or(0.0);

        let flame_us = bench_flame_for(op, shape_name).unwrap_or(0.0);

        let ratio = if pytorch_us > 0.0 && flame_us > 0.0 {
            format!("{:.2}x", flame_us / pytorch_us)
        } else {
            "—".to_string()
        };

        println!(
            "{:<35} {:<28} {:>12.1} {:>12.1} {:>10}",
            op, shape_name, pytorch_us, flame_us, ratio
        );
    }
}
